import { Inter } from "next/font/google";
import "./globals.css";
import { NextAuthProvider } from "@/components/authProvider";
import Footer from "@/components/footer";
import QueryProvider from "@/components/queryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <QueryProvider>
            {children}
            <Footer />
          </QueryProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
